services:
  n8n:
    image: n8nio/n8n
    container_name: n8n-app
#    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=vface.id.vn
      - MODE_ENV=production
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://vface.id.vn/
      - N8N_SECURE_COOKIE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_PROXY_HOPS=1
      - TZ=UTC+2
      - N8N_PUSH_BACKEND=sse
      - N8N_PUSH_BACKEND_WS=true  # Enable WebSocket for better stability
      - N8N_PUSH_BACKEND_WS_RECONNECT_TIMEOUT=5000  # Reconnect delay
      - N8N_PUSH_BACKEND_WS_KEEP_ALIVE_INTERVAL=20000  # Keep connection alive
#      - DB_TYPE=sqlite
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n_user
      - DB_POSTGRESDB_PASSWORD=n8n_password
    volumes:
      - /root/n8n/n8n_data:/home/node/.n8n  # Absolute path to ensure mounting
    user: "1000:1000" 
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    container_name: n8n-postgres
    restart: always
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n_user
      - POSTGRES_PASSWORD=n8n_password
    volumes:
      - /root/n8n/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: